import type { Config } from "tailwindcss";
import tailwindcssAnimate from "tailwindcss-animate";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#0F172A",
        "on-primary-container": "#7c839b",
        "on-surface": "#0F172A",
        "on-surface-variant": "#475569",
        "on-error": "#ffffff",
        "on-background": "#191c1e",
        "surface-container-high": "#e6e8ea",
        "surface-container-highest": "#e0e3e5",
        "surface-tint": "#565e74",
        surface: "#ffffff",
        "primary-fixed": "#dae2fd",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#d3e4fe",
        background: "#F8FAFC",
        "border-base": "#E2E8F0",
        "on-secondary-fixed-variant": "#38485d",
        "on-tertiary-fixed-variant": "#005137",
        "tertiary-fixed": "#85f8c4",
        success: "#22C55E",
        "tertiary-fixed-dim": "#68dba9",
        "on-tertiary-fixed": "#002114",
        outline: "#76777d",
        "inverse-surface": "#2d3133",
        "primary-fixed-dim": "#bec6e0",
        info: "#0EA5E9",
        "on-secondary-container": "#54647a",
        "secondary-container": "#d0e1fb",
        secondary: "#505f76",
        "surface-container": "#eceef0",
        "on-primary": "#ffffff",
        "tertiary-container": "#059669",
        warning: "#EAB308",
        "inverse-on-surface": "#eff1f3",
        "surface-container-lowest": "#ffffff",
        "surface-variant": "#e0e3e5",
        primary: "#000000",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed": "#0b1c30",
        "secondary-fixed-dim": "#b7c8e1",
        "error-container": "#ffdad6",
        "surface-container-low": "#f2f4f6",
        "inverse-primary": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-tertiary": "#ffffff",
        error: "#EF4444",
        "outline-variant": "#c6c6cd",
        "on-tertiary-container": "#059669",
        "on-secondary": "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        "2xl": "48px",
        "3xl": "64px",
      },
      fontFamily: {
        display: ["Plus Jakarta Sans", "sans-serif"],
        h1: ["Plus Jakarta Sans", "sans-serif"],
        h2: ["Plus Jakarta Sans", "sans-serif"],
        h3: ["Plus Jakarta Sans", "sans-serif"],
        h4: ["Plus Jakarta Sans", "sans-serif"],
        body: ["DM Sans", "sans-serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        caption: ["DM Sans", "sans-serif"],
        code: ["Fira Code", "monospace"],
      },
      fontSize: {
        display: ["40px", { lineHeight: "1.15", fontWeight: "700" }],
        h1: ["32px", { lineHeight: "1.2", fontWeight: "700" }],
        "h1-mobile": ["24px", { lineHeight: "1.25", fontWeight: "700" }],
        h2: ["24px", { lineHeight: "1.25", fontWeight: "600" }],
        h3: ["20px", { lineHeight: "1.3", fontWeight: "600" }],
        h4: ["16px", { lineHeight: "1.35", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        body: ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        caption: ["12px", { lineHeight: "1.4", fontWeight: "500" }],
        code: ["14px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      boxShadow: {
        card: "0 4px 24px rgba(15, 23, 42, 0.05)",
        elevated: "0 8px 32px rgba(15, 23, 42, 0.07)",
        modal: "0 12px 48px rgba(15, 23, 42, 0.1)",
      },
      keyframes: {
        "slide-up": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
      },
      animation: {
        "slide-up": "slide-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
      },
    },
  },
  plugins: [tailwindcssAnimate],
};

export default config;
