CREATE INDEX "idx_account_transactions_org" ON "account_transactions" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_account_transactions_account" ON "account_transactions" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "idx_accounts_org" ON "accounts" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_consumables_log_org" ON "consumables_log" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_consumables_log_account" ON "consumables_log" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "idx_consumption_logs_org" ON "consumption_logs" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_consumption_logs_consumable" ON "consumption_logs" USING btree ("consumable_id");--> statement-breakpoint
CREATE INDEX "idx_customers_org" ON "customers" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_material_categories_org" ON "material_categories" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_material_subtypes_org" ON "material_subtypes" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_material_subtypes_category" ON "material_subtypes" USING btree ("category_id");--> statement-breakpoint
CREATE INDEX "idx_period_reports_org" ON "period_reports" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_items_org" ON "purchase_items" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_items_purchase" ON "purchase_items" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_items_subtype" ON "purchase_items" USING btree ("subtype_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_other_expenses_org" ON "purchase_other_expenses" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_other_expenses_purchase" ON "purchase_other_expenses" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_other_expenses_account" ON "purchase_other_expenses" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_payments_org" ON "purchase_payments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_payments_purchase" ON "purchase_payments" USING btree ("purchase_id");--> statement-breakpoint
CREATE INDEX "idx_purchase_payments_account" ON "purchase_payments" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "idx_purchases_org" ON "purchases" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_purchases_vendor" ON "purchases" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "idx_purchases_purchase_date" ON "purchases" USING btree ("purchase_date");--> statement-breakpoint
CREATE INDEX "idx_salary_advances_org" ON "salary_advances" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_salary_advances_worker" ON "salary_advances" USING btree ("worker_id");--> statement-breakpoint
CREATE INDEX "idx_salary_payments_org" ON "salary_payments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_salary_payments_worker" ON "salary_payments" USING btree ("worker_id");--> statement-breakpoint
CREATE INDEX "idx_sale_items_org" ON "sale_items" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_sale_items_sale" ON "sale_items" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "idx_sale_items_subtype" ON "sale_items" USING btree ("subtype_id");--> statement-breakpoint
CREATE INDEX "idx_sale_payments_org" ON "sale_payments" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_sale_payments_sale" ON "sale_payments" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX "idx_sale_payments_account" ON "sale_payments" USING btree ("account_id");--> statement-breakpoint
CREATE INDEX "idx_sales_org" ON "sales" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_sales_customer" ON "sales" USING btree ("customer_id");--> statement-breakpoint
CREATE INDEX "idx_sales_sale_date" ON "sales" USING btree ("sale_date");--> statement-breakpoint
CREATE INDEX "idx_scrap_pool_org" ON "scrap_pool" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_scrap_pool_reference_id" ON "scrap_pool" USING btree ("reference_id");--> statement-breakpoint
CREATE INDEX "idx_sessions_user" ON "sessions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX "idx_stock_ledger_org" ON "stock_ledger" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_stock_ledger_subtype" ON "stock_ledger" USING btree ("subtype_id");--> statement-breakpoint
CREATE INDEX "idx_stock_ledger_movement_date" ON "stock_ledger" USING btree ("movement_date");--> statement-breakpoint
CREATE INDEX "idx_users_org" ON "users" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_vendors_org" ON "vendors" USING btree ("organization_id");--> statement-breakpoint
CREATE INDEX "idx_workers_org" ON "workers" USING btree ("organization_id");